import "./style.scss";

import { createClient, groq } from "next-sanity";

import Link from "next/link";

import Header from "../components/Header";
import Projects from "../components/client/Projects";

export const metadata = {
  title: "Create Next App yo",
  description: "Generated by create next app",
};

const getData = async () => {
  const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID; // "pv8y60vp"
  const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET; // "production"
  const apiVersion = process.env.NEXT_PUBLIC_SANITY_API_VERSION; // "2022-11-16"

  const client = createClient({
    projectId,
    dataset,
    apiVersion, // https://www.sanity.io/docs/api-versioning
    useCdn: true, // if you're using ISR or only static generation at build time then you can set this to `false` to guarantee no stale content
  });

  const data = await client.fetch(groq`*[_type == "homePage" ][0] {
  projects[]-> {
    _id,
    "title": coalesce(title, false),
    "body": coalesce(body, false),
    "images": coalesce(images.images, false),
    "credits": coalesce(credits, false),
    "link": coalesce(link, false),
    "featuredVideo": coalesce(featuredVideo, false),  
    "mainImage": coalesce(mainImage, false),
    "categories": coalesce(categories[]->{
      _id,
      title
    }, false),
    "slug": coalesce(slug.current, false),
    "client": coalesce(client, false),
  }
}`);

  return data;
};

export default async function RootLayout({ children }) {
  const { projects } = await getData();
  return (
    <html lang="en">
      <body>
        <Header />
        <section className="wrapper text-jumbo text-right py-24 md:py-48">
          <h1>Crafting Beautiful frontend experiences</h1>
        </section>
        <div>
          <Projects projects={projects} />
        </div>
        <div>{children}</div>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
