import "./style.scss";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Jumbotron from "@/components/client/Jumbotron";
import Projects from "@/components/client/Projects";

import { getData } from "@/utils/sanity";

export const metadata = {
  title: "Create Next App yo",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { projects } = await getData();
  return (
    <html lang="en">
      <body className="w-full overflow-x-hidden">
        <Header />
        <section className="py-24 text-right wrapper md:py-40">
          <Jumbotron />
        </section>
        <div className="w-full h-96">
          <Projects projects={projects} />
        </div>
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
